version: "2"

services:
  node:
    build: .
    working_dir: /usr/src/app
    environment:
        - NODE_ENV=production #development
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "npm start"
  #   links:
  #     - mongo
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   ports:
  #     - "27017:27017"